export const companiesCarburant = [
  {
    id: "1",
    name: "Petro RDC",
    description: "Station-service moderne.",
    logo: "https://cdn-icons-png.flaticon.com/512/908/908286.png",
    location: "Kinshasa, Gombe",
    defaultFuel: "Essence Super 95",
    pricePerLiter: 1.2,
    products: [
      { id: "c1", name: "Essence Super 95", pricePerLiter: 1.2, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c2", name: "Diesel", pricePerLiter: 1.0, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c3", name: "Lubrifiant Moteur 1L", pricePerLiter: 15, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2912/2912603.png" },
    ],
  },
  {
    id: "2",
    name: "Total Energy Plus",
    description: "Carburant et lubrifiants.",
    logo: "https://cdn-icons-png.flaticon.com/512/1995/1995574.png",
    location: "Kinshasa, Limete",
    defaultFuel: "Essence Super 95",
    pricePerLiter: 1.2,
    products: [
      { id: "c6", name: "Essence Super 95", pricePerLiter: 1.25, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c7", name: "Diesel", pricePerLiter: 1.05, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c8", name: "Lubrifiant 5L", pricePerLiter: 70, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2912/2912603.png" },
    ],
  },
  {
    id: "3",
    name: "Fuel Express",
    description: "Vente carburant rapide.",
    logo: "https://cdn-icons-png.flaticon.com/512/1046/1046857.png",
    location: "Kinshasa, Bandalungwa",
    defaultFuel: "Essence Super 98",
    pricePerLiter: 1.2,
    products: [
      { id: "c11", name: "Essence Super 98", pricePerLiter: 1.4, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c12", name: "Diesel Premium", pricePerLiter: 1.2, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
    ],
  },
  {
    id: "4",
    name: "Oil Center",
    description: "Distribution carburant.",
    logo: "https://cdn-icons-png.flaticon.com/512/908/908286.png",
    location: "Kinshasa, Kintambo",
    defaultFuel: "Essence Super 95",
    pricePerLiter: 1.2,
    products: [
      { id: "c16", name: "Essence Super 95", pricePerLiter: 1.2, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c17", name: "Diesel", pricePerLiter: 1.0, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
    ],
  },
  {
    id: "5",
    name: "Gas Africa",
    description: "Solutions carburant.",
    logo: "https://cdn-icons-png.flaticon.com/512/908/908286.png",
    location: "Kinshasa, Ngaliema",
    defaultFuel: "Essence Super 98",
    pricePerLiter: 1.2,
    products: [
      { id: "c21", name: "Essence Super 98", pricePerLiter: 1.35, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
      { id: "c22", name: "Diesel Premium", pricePerLiter: 1.2, unit: "litre", image: "https://cdn-icons-png.flaticon.com/512/2921/2921829.png" },
    ],
  },
];
